# Generated by Django 5.2.8 on 2025-11-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_critique", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesubmission",
            name="campaign_tag",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional campaign tag for grouping related articles",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="articlesubmission",
            name="user_context",
            field=models.TextField(
                blank=True, help_text="Optional user-provided context about the article"
            ),
        ),
        migrations.AlterField(
            model_name="quickresponse",
            name="response_type",
            field=models.CharField(
                choices=[
                    ("tweet", "Tweet"),
                    ("thread", "Thread"),
                    ("letter", "Letter to Editor"),
                    ("comment", "Article Comment"),
                    ("x_reply", "X/Twitter Reply"),
                    ("bluesky_post", "Bluesky Post"),
                    ("bluesky_thread", "Bluesky Thread"),
                    ("reddit_main", "Reddit Main Post"),
                    ("reddit_supportive", "Reddit Supportive Reply"),
                    ("reddit_sceptic", "Reddit Sceptic Reply"),
                    ("reddit_hostile", "Reddit Hostile Reply"),
                    ("reddit_summary", "Reddit Summary Reply"),
                    ("generic_comment", "Generic Comment"),
                ],
                max_length=20,
            ),
        ),
    ]
