# Generated by Django 5.0 on 2025-11-23 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factcheck", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Claim Comment",
                "verbose_name_plural": "Claim Comments",
                "db_table": "fact_check_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimOfTheDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("featured_date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Claim of the Day",
                "verbose_name_plural": "Claims of the Day",
                "db_table": "fact_check_claim_of_day",
                "ordering": ["-featured_date"],
            },
        ),
        migrations.CreateModel(
            name="ClaimOfTheMinute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minute_timestamp", models.DateTimeField()),
                ("upvotes_at_time", models.IntegerField()),
            ],
            options={
                "verbose_name": "Claim of the Minute",
                "verbose_name_plural": "Claims of the Minute",
                "db_table": "fact_check_claim_of_minute",
                "ordering": ["-minute_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("first_claim", "First Claim Submitted"),
                            ("verified_expert", "Verified Expert"),
                            ("hot_streak_5", "Hot Streak: 5 in a row"),
                            ("hot_streak_10", "Hot Streak: 10 in a row"),
                            ("claim_of_day", "Claim of the Day"),
                            ("claim_of_minute", "Claim of the Minute"),
                            ("upvote_king", "100 Upvotes Earned"),
                            ("severity_master", "Severity Accuracy 90%+"),
                            ("prolific_checker", "50 Claims Submitted"),
                            ("legendary_checker", "100 Claims Submitted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
                "db_table": "fact_check_user_badges",
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Follow",
                "verbose_name_plural": "User Follows",
                "db_table": "fact_check_user_follows",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_claims_submitted", models.IntegerField(default=0)),
                ("total_upvotes_earned", models.IntegerField(default=0)),
                ("claims_fact_checked", models.IntegerField(default=0)),
                ("severity_accuracy_score", models.FloatField(default=0.0)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                ("experience_points", models.IntegerField(default=0)),
                ("hot_streak_count", models.IntegerField(default=0)),
                ("max_hot_streak", models.IntegerField(default=0)),
                ("claims_of_the_minute", models.IntegerField(default=0)),
                ("claims_of_the_day", models.IntegerField(default=0)),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "fact_check_user_profiles",
            },
        ),
        migrations.RenameIndex(
            model_name="factcheckrequest",
            new_name="fact_check__status_0516e2_idx",
            old_name="fact_check_requests_status_idx",
        ),
        migrations.RenameIndex(
            model_name="factcheckrequest",
            new_name="fact_check__user_id_d98ab8_idx",
            old_name="fact_check_requests_user_idx",
        ),
        migrations.RenameIndex(
            model_name="factcheckrequest",
            new_name="fact_check__created_3bc3d4_idx",
            old_name="fact_check_requests_created_at_idx",
        ),
        migrations.AddField(
            model_name="claimcomment",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="factcheck.factcheckrequest",
            ),
        ),
        migrations.AddField(
            model_name="claimcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factcheck_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claimoftheday",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_features",
                to="factcheck.factcheckrequest",
            ),
        ),
        migrations.AddField(
            model_name="claimoftheminute",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minute_features",
                to="factcheck.factcheckrequest",
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factcheck_badges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userfollow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factcheck_following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userfollow",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factcheck_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factcheck_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="claimoftheminute",
            index=models.Index(
                fields=["minute_timestamp"], name="fact_check__minute__fde547_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("user", "badge_type")},
        ),
        migrations.AlterUniqueTogether(
            name="userfollow",
            unique_together={("follower", "following")},
        ),
    ]
