# Generated by Django 5.0 on 2025-11-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="achievement",
            new_name="achievement_user_id_9445b4_idx",
            old_name="achievements_user_idx",
        ),
        migrations.RenameIndex(
            model_name="achievement",
            new_name="achievement_achieve_813271_idx",
            old_name="achievements_achievement_type_idx",
        ),
        migrations.RenameIndex(
            model_name="useraction",
            new_name="user_action_user_id_3ca348_idx",
            old_name="user_actions_user_idx",
        ),
        migrations.RenameIndex(
            model_name="useraction",
            new_name="user_action_action__efde8d_idx",
            old_name="user_actions_action_type_idx",
        ),
        migrations.RenameIndex(
            model_name="useraction",
            new_name="user_action_created_258ebf_idx",
            old_name="user_actions_created_at_idx",
        ),
    ]
