# Generated by Django 5.0 on 2025-11-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="users_email_4b85f2_idx",
            old_name="users_email_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_team_id_76fc8d_idx",
            old_name="users_team_idx",
        ),
    ]
