# Generated by Django 5.0 on 2025-11-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rebuttal", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="rebuttal",
            new_name="rebuttals_version_d06202_idx",
            old_name="rebuttals_version_idx",
        ),
        migrations.RenameIndex(
            model_name="rebuttal",
            new_name="rebuttals_publish_cd3f6b_idx",
            old_name="rebuttals_published_idx",
        ),
    ]
