# Generated by Django 5.2.8 on 2025-11-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_critique", "0003_add_manual_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="critiqueresponse",
            name="bluesky_thread",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Bluesky thread posts: [{role, text}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="critiqueresponse",
            name="conversation_spec",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured conversation spec: {context_summary, key_points, tone, steps}",
            ),
        ),
        migrations.AddField(
            model_name="critiqueresponse",
            name="reddit_conversation",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Reddit structure: {main_post, supportive_reply, curious_sceptic_reply, hostile_monetarist_reply, summary_reply}",
            ),
        ),
        migrations.AddField(
            model_name="socialmediacritique",
            name="campaign_tag",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional campaign tag for grouping related critiques",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="socialmediacritique",
            name="user_context",
            field=models.TextField(
                blank=True, help_text="Optional user-provided context about the content"
            ),
        ),
        migrations.AlterField(
            model_name="shareablereply",
            name="reply_type",
            field=models.CharField(
                choices=[
                    ("short", "Short Reply"),
                    ("thread", "Thread"),
                    ("summary", "Summary Card"),
                    ("x_reply", "X/Twitter Reply"),
                    ("bluesky_post", "Bluesky Post"),
                    ("bluesky_thread", "Bluesky Thread"),
                    ("reddit_main", "Reddit Main Post"),
                    ("reddit_supportive", "Reddit Supportive Reply"),
                    ("reddit_sceptic", "Reddit Sceptic Reply"),
                    ("reddit_hostile", "Reddit Hostile Reply"),
                    ("reddit_summary", "Reddit Summary Reply"),
                    ("generic_comment", "Generic Comment"),
                ],
                max_length=20,
            ),
        ),
    ]
