# Generated by Django 5.2.8 on 2025-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_critique", "0004_critiqueresponse_bluesky_thread_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediacritique",
            name="source_author_bio",
            field=models.TextField(
                blank=True, help_text="Bio/description of the original poster"
            ),
        ),
        migrations.AddField(
            model_name="socialmediacritique",
            name="source_author_follower_count",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Follower count of the original poster",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="socialmediacritique",
            name="source_author_handle",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Social media handle of the original poster (e.g., @username)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="socialmediacritique",
            name="theme_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of theme tags (e.g., household_myth, bond_market, inflation, etc.)",
            ),
        ),
    ]
