# Generated by Django 5.0 on 2025-11-23 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_date",
                    models.DateField(help_text="Date of the misinformation"),
                ),
                (
                    "programme_name",
                    models.CharField(
                        help_text="Programme, show, or article name", max_length=200
                    ),
                ),
                (
                    "presenter_journalist",
                    models.CharField(
                        blank=True,
                        help_text="Presenter, journalist, or author",
                        max_length=200,
                    ),
                ),
                (
                    "timestamp",
                    models.CharField(
                        blank=True,
                        help_text="Timestamp in programme (e.g., 14:23)",
                        max_length=20,
                    ),
                ),
                (
                    "claim_description",
                    models.TextField(
                        help_text="Describe the misinformation or misleading claim"
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True, help_text="Additional context about the incident"
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "Minor"),
                            (2, "Moderate"),
                            (3, "Serious"),
                            (4, "Very Serious"),
                            (5, "Severe"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "preferred_tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("academic", "Academic"),
                            ("passionate", "Passionate"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Letter Generation"),
                            ("generated", "Letter Generated"),
                            ("sent", "Sent"),
                            ("responded", "Responded To"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "incident_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hash of incident for tracking duplicate complaints",
                        max_length=64,
                    ),
                ),
                (
                    "complaint_number_for_incident",
                    models.IntegerField(
                        default=1,
                        help_text="Which complaint number is this for this incident",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint",
                "verbose_name_plural": "Complaints",
                "db_table": "media_complaints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField(help_text="Full letter body")),
                (
                    "variation_strategy",
                    models.CharField(
                        choices=[
                            ("correction", "Request Correction"),
                            ("training", "Request Staff Training"),
                            ("policy", "Request Policy Review"),
                            ("investigation", "Request Investigation"),
                            ("accountability", "Emphasize Accountability"),
                        ],
                        help_text="Which rhetorical strategy was used",
                        max_length=30,
                    ),
                ),
                (
                    "tone_used",
                    models.CharField(
                        help_text="Tone used in generation", max_length=20
                    ),
                ),
                (
                    "mmt_points_included",
                    models.JSONField(
                        default=list,
                        help_text="List of MMT points addressed in the letter",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_to_email", models.EmailField(blank=True, max_length=254)),
                ("response_received", models.BooleanField(default=False)),
                ("response_date", models.DateField(blank=True, null=True)),
                ("response_summary", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "complaint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letter",
                        to="media_complaints.complaint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint Letter",
                "verbose_name_plural": "Complaint Letters",
                "db_table": "complaint_letters",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaOutlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("tv", "Television"),
                            ("radio", "Radio"),
                            ("print", "Print"),
                            ("online", "Online"),
                            ("social", "Social Media"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Primary contact email for complaints", max_length=254
                    ),
                ),
                (
                    "complaints_dept_email",
                    models.EmailField(
                        blank=True,
                        help_text="Specific complaints department email",
                        max_length=254,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "regulator",
                    models.CharField(
                        blank=True, help_text="e.g., Ofcom, IPSO", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Media Outlet",
                "verbose_name_plural": "Media Outlets",
                "db_table": "media_outlets",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["media_type"], name="media_outle_media_t_d86e27_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="media_outle_is_acti_b9e4db_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplaintStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_complaints_filed", models.IntegerField(default=0)),
                ("complaints_sent", models.IntegerField(default=0)),
                ("responses_received", models.IntegerField(default=0)),
                ("first_complaint_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaint_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "most_active_outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_complainers",
                        to="media_complaints.mediaoutlet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint Statistics",
                "verbose_name_plural": "Complaint Statistics",
                "db_table": "complaint_stats",
            },
        ),
        migrations.AddField(
            model_name="complaint",
            name="outlet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="media_complaints.mediaoutlet",
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["user"], name="media_compl_user_id_dca8a9_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["outlet"], name="media_compl_outlet__e99fe0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["status"], name="media_compl_status_bb9d33_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["incident_date"], name="media_compl_inciden_752cd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["created_at"], name="media_compl_created_b693b0_idx"
            ),
        ),
    ]
