# Generated by Django 5.0 on 2025-11-23 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_complaints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutletSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("tv", "Television"),
                            ("radio", "Radio"),
                            ("print", "Print"),
                            ("online", "Online"),
                            ("social", "Social Media"),
                        ],
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True, help_text="Official website")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Why this outlet should be added"
                    ),
                ),
                (
                    "suggested_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="AI-suggested contact email",
                        max_length=254,
                    ),
                ),
                (
                    "suggested_complaints_email",
                    models.EmailField(
                        blank=True,
                        help_text="AI-suggested complaints email",
                        max_length=254,
                    ),
                ),
                (
                    "suggested_regulator",
                    models.CharField(
                        blank=True, help_text="AI-suggested regulator", max_length=100
                    ),
                ),
                (
                    "research_notes",
                    models.TextField(blank=True, help_text="AI research findings"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Research"),
                            ("researched", "Research Complete"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("created", "Outlet Created"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Admin review notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_outlet_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlet_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Outlet Suggestion",
                "verbose_name_plural": "Outlet Suggestions",
                "db_table": "outlet_suggestions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="outlet_sugg_status_55f0ac_idx"
                    ),
                    models.Index(
                        fields=["user"], name="outlet_sugg_user_id_a3cfa9_idx"
                    ),
                ],
            },
        ),
    ]
