# Generated by Django 5.2.8 on 2025-11-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_complaints", "0003_seed_media_outlets"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="campaign_tag",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional campaign tag for grouping related complaints",
                max_length=100,
            ),
        ),
    ]
