# Generated by Django 5.0 on 2025-11-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bingocard",
            new_name="bingo_cards_user_id_24f138_idx",
            old_name="bingo_cards_user_idx",
        ),
        migrations.RenameIndex(
            model_name="bingocard",
            new_name="bingo_cards_complet_cd5d91_idx",
            old_name="bingo_cards_completed_idx",
        ),
        migrations.RenameIndex(
            model_name="bingophrase",
            new_name="bingo_phras_difficu_def555_idx",
            old_name="bingo_phrases_difficulty_idx",
        ),
        migrations.RenameIndex(
            model_name="bingosquare",
            new_name="bingo_squar_card_id_921ce6_idx",
            old_name="bingo_squares_card_idx",
        ),
        migrations.RenameIndex(
            model_name="bingosquare",
            new_name="bingo_squar_marked_be9625_idx",
            old_name="bingo_squares_marked_idx",
        ),
    ]
